Issue #SB-26780 feat: Secure API - User profile update as private end point
Sunbird-Ed/nodebb-plugin-sunbird-api pull request #42
Opened 2021-10-22 12:10 UTC by kamaleeswary

2021-10-22 12:59 UTC, vinukumar-vs requested changes

2021-10-22 12:59 UTC, vinukumar-vs commented on index.js
> +  const isRequiredParamsMissing = await util.checkRequiredParameters(req, res, requiredParams, userData);
variable name is right? 
below if condition should work when isRequiredParamsPresent then call the API to update

2021-10-25 04:10 UTC, kamaleeswary commented on index.js
> +  const isRequiredParamsMissing = await util.checkRequiredParameters(req, res, requiredParams, userData);
ok

2021-10-25 08:55 UTC, VenkatKadiveti approved these changes

2021-10-25 09:42 UTC, vinukumar-vs approved these changes

2021-10-25 09:42 UTC, merged